### ISSUE TITLE
Thermostats not works in HC2 4.620 (latest)

### ISSUE THREAD

**Issue by vvsokolov** [ilcato/homebridge-fibaro-home-center#59]
Thermostats not works in HC2 4.620 (latest)
Any thermostat changes in the Home-app are not reflected in HC2 4.620 (latest version) and vice versa.
Yes, I did a full reconfiguration of the thermostat after installing the latest version.

**Comment by vvsokolov** [comment]
@ilcato , could you please say something about possible terms of fixing it ?

**Comment by ChrisBuHa** [comment]
@ilcato any updates on that bug? Would love to use my thermostats via homebridge. 

Thank you very much for your great work! I absolutly enjoy to control all my zwave devices (switches, roller shutters) via home kit.  Only the thermostats do not work 😔

**Comment by ilcato** [comment]
@vvsokolov , @ChrisBuHa: Working on a climate zones integration instead of single thermostats.

**Comment by ilcato** [comment]
@vvsokolov , @ChrisBuHa: can you test the 1.2.2-beta.0 version ?

**Comment by ChrisBuHa** [comment]
@ilcato Of cause I can do that. Just need a short introduction how to install the beta version. I am quite new and not very experienced.

**Comment by vvsokolov** [comment]
> @vvsokolov , @ChrisBuHa: can you test the 1.2.2-beta.0 version ?

Yes, of cause! Is it possible now by installing
npm install -g homebridge-fibaro-home-center@1a79331  ?

**Comment by ilcato** [comment]
npm install -g homebridge-fibaro-home-center@beta

**Comment by ChrisBuHa** [comment]
@ilcato 

Installed the beta, but get the following error message during start up:

[06/12/2021, 09:54:36] Homebridge v1.3.8 (HAP v0.9.7) (Homebridge 7B44) is running on port 51590.
[06/12/2021, 09:54:38] [Hue] Lampe Hannah: set homekit supported transition configuration to {"configuration":[{"iid":11,"characteristic":1},{"iid":13,"characteristic":2}]}
[06/12/2021, 09:54:38] [Hue] Lampe Till: set homekit supported transition configuration to {"configuration":[{"iid":11,"characteristic":1},{"iid":13,"characteristic":2}]}
[06/12/2021, 09:54:38] [Hue] Lampe Sauna: set homekit supported transition configuration to {"configuration":[{"iid":11,"characteristic":1},{"iid":13,"characteristic":2}]}
[06/12/2021, 09:54:38] [Hue] Lampe Schreibtisch: set homekit supported transition configuration to {"configuration":[{"iid":11,"characteristic":1},{"iid":13,"characteristic":2}]}
[06/12/2021, 09:54:40] [Hue] goodbye
[06/12/2021, 09:54:40] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[06/12/2021, 09:54:45] [HB Supervisor] Restarting Homebridge...
[06/12/2021, 09:54:45] [HB Supervisor] Starting Homebridge with extra flags: -I
[06/12/2021, 09:54:45] [HB Supervisor] Started Homebridge v1.3.8 with PID: 6217
[06/12/2021, 09:54:46] Loaded config.json with 2 accessories and 5 platforms.
[06/12/2021, 09:54:46] Loaded 44 cached accessories from cachedAccessories.
[06/12/2021, 09:54:46] ---
[06/12/2021, 09:54:47] Loaded plugin: homebridge-config-ui-x@4.41.3
[06/12/2021, 09:54:47] Registering platform 'homebridge-config-ui-x.config'
[06/12/2021, 09:54:47] ---
[06/12/2021, 09:54:47] Loaded plugin: homebridge-eveatmo@0.6.4
[06/12/2021, 09:54:47] Registering platform 'homebridge-eveatmo.eveatmo'
[06/12/2021, 09:54:47] ---
[06/12/2021, 09:54:48] Loaded plugin: homebridge-fibaro-home-center@1.2.2-beta.0
[06/12/2021, 09:54:48] Registering platform 'homebridge-fibaro-home-center.FibaroHC'
[06/12/2021, 09:54:48] ---
[06/12/2021, 09:54:48] Loaded plugin: homebridge-homeconnect@0.23.3
[06/12/2021, 09:54:48] Registering platform 'homebridge-homeconnect.HomeConnect'
[06/12/2021, 09:54:48] ---
[06/12/2021, 09:54:50] Loaded plugin: homebridge-hue@0.13.29
[06/12/2021, 09:54:50] Registering platform 'homebridge-hue.Hue'
[06/12/2021, 09:54:50] ---
[06/12/2021, 09:54:50] Loaded plugin: homebridge-pihole@0.3.5
[06/12/2021, 09:54:50] Registering accessory 'homebridge-pihole.Pihole'
[06/12/2021, 09:54:50] ---
[06/12/2021, 09:54:50] Loaded plugin: homebridge-raspberrypi-temperature@0.0.8
[06/12/2021, 09:54:50] Registering accessory 'homebridge-raspberrypi-temperature.RaspberryPiTemperature'
[06/12/2021, 09:54:50] ---
[06/12/2021, 09:54:50] Loading 5 platforms...
[06/12/2021, 09:54:50] [Config] Initializing config platform...
[06/12/2021, 09:54:50] [Config] Running in Service Mode
[06/12/2021, 09:54:50] [Hue] Initializing Hue platform...
[06/12/2021, 09:54:50] [Hue] homebridge-hue v0.13.29, node v16.13.0, homebridge v1.3.8
[06/12/2021, 09:54:50] [eveatmo platform] Initializing eveatmo platform...
[06/12/2021, 09:54:52] [eveatmo platform] Loading new data from API for: weatherstation
[06/12/2021, 09:54:52] [eveatmo platform] Loading new data from API for: airquality
[06/12/2021, 09:54:52] [FibaroHC] Initializing FibaroHC platform...
[06/12/2021, 09:54:52] [HomeConnect] Initializing HomeConnect platform...
[06/12/2021, 09:54:52] [HomeConnect] new HomeConnectPlatform
[06/12/2021, 09:54:52] Loading 2 accessories...
[06/12/2021, 09:54:52] [RaspberryPi CPU Temperature] Initializing RaspberryPiTemperature accessory...
[06/12/2021, 09:54:52] [Pihole] Initializing Pihole accessory...
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Wall Plug
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Thermostat KF
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Temperatur KF
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Thermostat SR
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Temperatur SR
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Thermostat HZ
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Temperatur HZ
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Rolladen Essbereich
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Garagentor
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Rolladen Terrasse
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Rolladen Fensterbank
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Fenstersensor Hannah
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Rollladen Küche
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Rollladen Till
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Taster Garagentor
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Thermostat KZ Hanna
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Temperatur KZ Hanna
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Lampe Badezimmer
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Thermostat ES
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Temperatur ES
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Thermostat KZ Till
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Temperatur KZ Till
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Fester ES
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Temp FS  ES
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Fenster KZ Till
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Temp FS KZ Till
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Fenster Badezimmer
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Temp FS Badezimmer
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Lichtschalter Till
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Steckdose Till
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Steckdose Hannah
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Girlande Treppenhaus
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Lichtschalter Flur
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Lichtschalter Esszim
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Lichtschalter ES
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Steckdose ES
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Lichtschalter Hannah
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Lichtschalter DG
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Steckdose DG
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Thermostat DG
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Temperatur DG
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Thermostat BZ
[06/12/2021, 09:54:52] [FibaroHC] Loading accessory from cache: Temperatur BZ
[06/12/2021, 09:54:52] [HomeConnect] Restored 1 cached accessories
[06/12/2021, 09:54:52] [HomeConnect] Starting events stream for all appliances
[06/12/2021, 09:54:52] [Hue] Philips hue: Signify Netherlands B.V. BSB002 bridge v1948086000, api v1.48.0
[06/12/2021, 09:54:52] [FibaroHC] Error getting data from Home Center:  Error: Not Implemented
    at Request.callback (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:879:15)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:1130:18)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  status: 501,
  response: <ref *1> Response {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 501,
      statusMessage: 'Not Implemented',
      client: [Socket],
      _consuming: true,
      _dumped: false,
      req: [ClientRequest],
      text: '',
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 8,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      _enableHttp2: false,
      _agent: false,
      _formData: null,
      method: 'GET',
      url: 'http://192.168.178.68/api/panels/climate?detailed=false',
      _header: [Object],
      header: [Object],
      writable: true,
      _redirects: 0,
      _maxRedirects: 5,
      cookies: '',
      qs: {},
      _query: [],
      qsRaw: [],
      _redirectList: [],
      _streamRequest: false,
      throttle: [Throttle],
      serial: false,
      _maskedEnd: [Function (anonymous)],
      end: [Function (anonymous)],
      _ca: undefined,
      _maskedCallback: [Function (anonymous)],
      req: [ClientRequest],
      protocol: 'http:',
      host: '192.168.178.68',
      _endCalled: true,
      _callback: [Function: cleanup],
      _fullfilledPromise: [Promise],
      res: [IncomingMessage],
      _resBuffered: true,
      response: [Circular *1],
      called: true,
      [Symbol(kCapture)]: false
    },
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /api/panels/climate?detailed=false HTTP/1.1\r\n' +
        'Host: 192.168.178.68\r\n' +
        'Accept-Encoding: gzip, deflate\r\n' +
        'Authorization: Basic Y2hyaXN0LmJ1c2NobWFubkBnbWFpbC5jb206UGo0ZjdLREkyQHlQZmUy\r\n' +
        'accept: json\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/panels/climate?detailed=false',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '192.168.178.68',
      protocol: 'http:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    text: '',
    body: {},
    files: undefined,
    buffered: true,
    headers: {
      server: 'nginx/1.8.0',
      date: 'Mon, 06 Dec 2021 08:54:52 GMT',
      'transfer-encoding': 'chunked',
      connection: 'close'
    },
    header: {
      server: 'nginx/1.8.0',
      date: 'Mon, 06 Dec 2021 08:54:52 GMT',
      'transfer-encoding': 'chunked',
      connection: 'close'
    },
    statusCode: 501,
    status: 501,
    statusType: 5,
    info: false,
    ok: false,
    redirect: false,
    clientError: false,
    serverError: true,
    error: Error: cannot GET /api/panels/climate?detailed=false (501)
        at Response.toError (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/response.js:95:15)
        at Response._setStatusProperties (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/response-base.js:126:48)
        at new Response (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/response.js:41:8)
        at Request._emitResponse (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:928:20)
        at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:1130:38)
        at IncomingMessage.emit (node:events:402:35)
        at endReadableNT (node:internal/streams/readable:1343:12)
        at processTicksAndRejections (node:internal/process/task_queues:83:21) {
      status: 501,
      text: '',
      method: 'GET',
      path: '/api/panels/climate?detailed=false'
    },
    created: false,
    accepted: false,
    noContent: false,
    badRequest: false,
    unauthorized: false,
    notAcceptable: false,
    forbidden: false,
    notFound: false,
    unprocessableEntity: false,
    type: '',
    links: {},
    setEncoding: [Function: bound ],
    redirects: [],
    pipe: [Function (anonymous)],
    [Symbol(kCapture)]: false
  }
}
[06/12/2021, 09:54:52] Error: Not Implemented
    at Request.callback (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:879:15)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:1130:18)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by ilcato** [comment]
@ChrisBuHa, which home center do you have, and which firmware version. I'm testing on a HC3 with the latest fw version.

**Comment by ilcato** [comment]
@ChrisBuHa,@vvsokolov are you able to check which REST API does the HC2 expose related to climate panels?

**Comment by ChrisBuHa** [comment]
@ilcato: I am using a HC2 with firmware version 4.620. This is the latest available one.
I will try to find out the properties of the REST API of the climate panels.
Any clue how to do that? 😀

**Comment by ChrisBuHa** [comment]
![Home Center 2Lite REST API  FIBARO Manuals](https://user-images.githubusercontent.com/94866088/144837797-8f7c6fed-2a65-473b-b00a-b17899df5559.png)

found the following on the fibaro web page. Is it that what you are looking for?

**Comment by ilcato** [comment]
@ChrisBuHa, the documentation is incomplete. Try to connect with a browser to your HC2 with a url like this:

http://IP_HC2/docs or doc

From there you can call the API and see what it returns.

**Comment by ChrisBuHa** [comment]
@ilcato: Connected to HC2 as reccomended by you. Please find below the information regarding heating panel API

![POST Heating](https://user-images.githubusercontent.com/94866088/144871389-f2189fd6-2bb2-477a-b808-4248b4bdd8cd.png)
![PUT heating ID](https://user-images.githubusercontent.com/94866088/144871394-19931d04-8157-4b84-9af2-91864c9a4b0f.png)
![Delete heating ID](https://user-images.githubusercontent.com/94866088/144871395-79207537-e345-4d7f-a5ae-48a1f3a470dd.png)
![GET heating ID](https://user-images.githubusercontent.com/94866088/144871397-954ebc08-8216-4ab5-85f0-f9493638e447.png)
![GET Heating](https://user-images.githubusercontent.com/94866088/144871400-1f74f4a0-e99f-4051-befa-b056f89a0cec.png)

 {
      "path": "/panels/heating",
      "operations": [
        {
          "method": "GET",
          "summary": "Get a list of all available heating objects",
          "type": "GETTemperature",
          "nickname": "getHeatings",
          "parameters": []
        },
    {
          "method": "POST",
          "summary": "Create heating",
          "type": "string",
          "nickname": "createNotification",
          "parameters": [
            {
               "name": "body",

		      "description": "Heating object body",
		      "required": true,
		      "type": "GETAllTemperature",
		      "paramType": "body"
            }
          ],
			"responseMessages": [
            {
              "code": 400,
              "message": "Bad request"
            },
			{
              "code": 404,
              "message": "Not found"
            }
			]
        }
	]
},
    {
      "path": "/panels/heating/{heatingID}",
      "operations": [
        {
          "method": "GET",
          "summary": "Get heating object",
          "type": "GETAllTemperature",
          "nickname": "getHeating",
          "parameters": [
			{
			    "name":"heatingID",
               "description":"ID of an existing heating object",
               "required":true,
              "type": "integer",
			  "format": "int32",
               "paramType":"path"
			}
			]
        },
    {
          "method": "PUT",
          "summary": "Modify heating",
          "type": "void",
          "nickname": "modHeating",
          "parameters": [
			{
			    "name":"heatingID",
               "description":"ID of an existing heating object",
               "required":true,
              "type": "integer",
			  "format": "int32",
               "paramType":"path"
			},
            {
               "name": "body",
		      "description": "Heating object body",
		      "required": true,
		      "type": "GETAllTemperature",
		      "paramType": "body"
            }
          ],
			"responseMessages": [
            {
              "code": 400,
              "message": "Bad request"
            },
			{
              "code": 404,
              "message": "Not found"
            }
			]
        },
    {
          "method": "DELETE",
          "summary": "Delete heating",
          "type": "void",
          "nickname": "deleteHeating",
          "parameters": [
			{
			    "name":"heatingID",
               "description":"ID of an existing heating object",
               "required":true,
              "type": "integer",
			  "format": "int32",
               "paramType":"path"
			}
          ]
        }
      ]
    },

**Comment by ilcato** [comment]
@ChrisBuHa, can you install the updated beta? I implemented the old HC2 API, but I do not have an HC2. 
Repeat the command:
`npm install -g homebridge-fibaro-home-center@beta`
Thanks.

**Comment by ChrisBuHa** [comment]
@ilcato Do I have to install it via SSH or can I also you the terminal of the Homebridge UI? 
Do I just need to use exactly the comand or do i have to start with sudo? 

Sorry, as I mentioned I am not really experianced with it Just got my raspi 2 Weeks ago. But I am willing to learn ;-)

**Comment by ilcato** [comment]
@ChrisBuHa, via ssh with the same method you used before. Use sudo. Restart homebridge after that.

**Comment by ChrisBuHa** [comment]
@ilcato Have installed the beta as described by you. Still get an error message during start up.



[06/12/2021, 18:59:05] [FibaroHC] Error getting data from Home Center:  Error: Not Implemented
    at Request.callback (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:879:15)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:1130:18)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  status: 501,
  response: <ref *1> Response {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 501,
      statusMessage: 'Not Implemented',
      client: [Socket],
      _consuming: true,
      _dumped: false,
      req: [ClientRequest],
      text: '',
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 8,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      _enableHttp2: false,
      _agent: false,
      _formData: null,
      method: 'GET',
      url: 'http://192.168.178.68/api/panels/climate?detailed=false',
      _header: [Object],
      header: [Object],
      writable: true,
      _redirects: 0,
      _maxRedirects: 5,
      cookies: '',
      qs: {},
      _query: [],
      qsRaw: [],
      _redirectList: [],
      _streamRequest: false,
      throttle: [Throttle],
      serial: false,
      _maskedEnd: [Function (anonymous)],
      end: [Function (anonymous)],
      _ca: undefined,
      _maskedCallback: [Function (anonymous)],
      req: [ClientRequest],
      protocol: 'http:',
      host: '192.168.178.68',
      _endCalled: true,
      _callback: [Function: cleanup],
      _fullfilledPromise: [Promise],
      res: [IncomingMessage],
      _resBuffered: true,
      response: [Circular *1],
      called: true,
      [Symbol(kCapture)]: false
    },
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /api/panels/climate?detailed=false HTTP/1.1\r\n' +
        'Host: 192.168.178.68\r\n' +
        'Accept-Encoding: gzip, deflate\r\n' +
        'Authorization: Basic Y2hyaXN0LmJ1c2NobWFubkBnbWFpbC5jb206UGo0ZjdLREkyQHlQZmUy\r\n' +
        'accept: json\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/panels/climate?detailed=false',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '192.168.178.68',
      protocol: 'http:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    text: '',
    body: {},
    files: undefined,
    buffered: true,
    headers: {
      server: 'nginx/1.8.0',
      date: 'Mon, 06 Dec 2021 17:59:05 GMT',
      'transfer-encoding': 'chunked',
      connection: 'close'
    },
    header: {
      server: 'nginx/1.8.0',
      date: 'Mon, 06 Dec 2021 17:59:05 GMT',
      'transfer-encoding': 'chunked',
      connection: 'close'
    },
    statusCode: 501,
    status: 501,
    statusType: 5,
    info: false,
    ok: false,
    redirect: false,
    clientError: false,
    serverError: true,
    error: Error: cannot GET /api/panels/climate?detailed=false (501)
        at Response.toError (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/response.js:95:15)
        at Response._setStatusProperties (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/response-base.js:126:48)
        at new Response (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/response.js:41:8)
        at Request._emitResponse (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:928:20)
        at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:1130:38)
        at IncomingMessage.emit (node:events:402:35)
        at endReadableNT (node:internal/streams/readable:1343:12)
        at processTicksAndRejections (node:internal/process/task_queues:83:21) {
      status: 501,
      text: '',
      method: 'GET',
      path: '/api/panels/climate?detailed=false'
    },
    created: false,
    accepted: false,
    noContent: false,
    badRequest: false,
    unauthorized: false,
    notAcceptable: false,
    forbidden: false,
    notFound: false,
    unprocessableEntity: false,
    type: '',
    links: {},
    setEncoding: [Function: bound ],
    redirects: [],
    pipe: [Function (anonymous)],
    [Symbol(kCapture)]: false
  }
}
[06/12/2021, 18:59:05] Error: Not Implemented
    at Request.callback (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:879:15)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:1130:18)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[06/12/2021, 18:59:05] Got SIGTERM, shutting down Homebridge...

**Comment by ilcato** [comment]
@ChrisBuHa, made another version. Can you test ?

**Comment by ChrisBuHa** [comment]
@ilcato done. now the homebridge starts up correctly. For three of my heating zones (6,10,81) I can find error messages in the log file. 

![heating zones homecenter](https://user-images.githubusercontent.com/94866088/144908141-b7dd1d38-908f-4b73-8ba9-c955f30bd57c.png)
Fo the heating zones in gray I got the error messages. But of cause also for the other ones the target values are not correct. They should not be 0 degree. :-)

[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  4  parameter: Current Heating Cooling State
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  4  parameter: Target Heating Cooling State
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  4  parameter: Current Temperature
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  4  parameter: Target Temperature
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  4  parameter: Temperature Display Units
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  5  parameter: Current Heating Cooling State
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  5  parameter: Target Heating Cooling State
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  5  parameter: Current Temperature
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  5  parameter: Target Temperature
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  5  parameter: Temperature Display Units
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  6  parameter: Current Heating Cooling State
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  6  parameter: Target Heating Cooling State
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  6  parameter: Current Temperature
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  6  parameter: Target Temperature
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  6  parameter: Temperature Display Units
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  7  parameter: Current Heating Cooling State
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  7  parameter: Target Heating Cooling State
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  7  parameter: Current Temperature
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  7  parameter: Target Temperature
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  7  parameter: Temperature Display Units
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  8  parameter: Current Heating Cooling State
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  8  parameter: Target Heating Cooling State
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  8  parameter: Current Temperature
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  8  parameter: Target Temperature
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  8  parameter: Temperature Display Units
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  9  parameter: Current Heating Cooling State
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  9  parameter: Target Heating Cooling State
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  9  parameter: Current Temperature
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  9  parameter: Target Temperature
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  9  parameter: Temperature Display Units
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  10  parameter: Current Heating Cooling State
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  10  parameter: Target Heating Cooling State
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  10  parameter: Current Temperature
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  10  parameter: Target Temperature
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  10  parameter: Temperature Display Units
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  81  parameter: Current Heating Cooling State
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  81  parameter: Target Heating Cooling State
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  81  parameter: Current Temperature
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  81  parameter: Target Temperature
[06/12/2021, 20:04:43] [FibaroHC] Getting value from device:  81  parameter: Temperature Display Units

[06/12/2021, 20:04:44] [FibaroHC] G1 - There was a problem getting value from:  6 - Err: Error: Not Found
[06/12/2021, 20:04:44] [FibaroHC] G1 - There was a problem getting value from:  6 - Err: Error: Not Found
[06/12/2021, 20:04:44] [FibaroHC] G1 - There was a problem getting value from:  6 - Err: Error: Not Found
[06/12/2021, 20:04:44] [FibaroHC] G1 - There was a problem getting value from:  6 - Err: Error: Not Found
[06/12/2021, 20:04:44] [FibaroHC] G1 - There was a problem getting value from:  6 - Err: Error: Not Found
[06/12/2021, 20:04:44] [FibaroHC] G1 - There was a problem getting value from:  10 - Err: Error: Not Found
[06/12/2021, 20:04:44] [FibaroHC] G1 - There was a problem getting value from:  10 - Err: Error: Not Found
[06/12/2021, 20:04:44] [FibaroHC] G1 - There was a problem getting value from:  10 - Err: Error: Not Found
[06/12/2021, 20:04:44] [FibaroHC] G1 - There was a problem getting value from:  10 - Err: Error: Not Found
[06/12/2021, 20:04:44] [FibaroHC] G1 - There was a problem getting value from:  10 - Err: Error: Not Found
[06/12/2021, 20:04:44] [FibaroHC] G1 - There was a problem getting value from:  81 - Err: Error: Not Found
[06/12/2021, 20:04:44] [FibaroHC] G1 - There was a problem getting value from:  81 - Err: Error: Not Found
[06/12/2021, 20:04:44] [FibaroHC] G1 - There was a problem getting value from:  81 - Err: Error: Not Found
[06/12/2021, 20:04:44] [FibaroHC] G1 - There was a problem getting value from:  81 - Err: Error: Not Found
[06/12/2021, 20:04:44] [FibaroHC] G1 - There was a problem getting value from:  81 - Err: Error: Not Found
[06/12/2021, 20:04:44] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:44] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:44] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:44] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:44] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:44] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:45] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:45] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:45] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:45] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:47] [FibaroHC] G1 - There was a problem getting value from:  6 - Err: Error: Not Found
[06/12/2021, 20:04:47] [FibaroHC] G1 - There was a problem getting value from:  6 - Err: Error: Not Found
[06/12/2021, 20:04:47] [FibaroHC] G1 - There was a problem getting value from:  6 - Err: Error: Not Found
[06/12/2021, 20:04:47] [FibaroHC] G1 - There was a problem getting value from:  6 - Err: Error: Not Found
[06/12/2021, 20:04:47] [FibaroHC] G1 - There was a problem getting value from:  6 - Err: Error: Not Found
[06/12/2021, 20:04:48] [FibaroHC] G1 - There was a problem getting value from:  10 - Err: Error: Not Found
[06/12/2021, 20:04:48] [FibaroHC] G1 - There was a problem getting value from:  10 - Err: Error: Not Found
[06/12/2021, 20:04:48] [FibaroHC] G1 - There was a problem getting value from:  10 - Err: Error: Not Found
[06/12/2021, 20:04:48] [FibaroHC] G1 - There was a problem getting value from:  10 - Err: Error: Not Found
[06/12/2021, 20:04:48] [FibaroHC] G1 - There was a problem getting value from:  10 - Err: Error: Not Found
[06/12/2021, 20:04:48] [FibaroHC] G1 - There was a problem getting value from:  81 - Err: Error: Not Found
[06/12/2021, 20:04:48] [FibaroHC] G1 - There was a problem getting value from:  81 - Err: Error: Not Found
[06/12/2021, 20:04:48] [FibaroHC] G1 - There was a problem getting value from:  81 - Err: Error: Not Found
[06/12/2021, 20:04:48] [FibaroHC] G1 - There was a problem getting value from:  81 - Err: Error: Not Found
[06/12/2021, 20:04:48] [FibaroHC] G1 - There was a problem getting value from:  81 - Err: Error: Not Found
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:48] [Hue] Philips hue: request 32: GET /lights
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:48] [Hue] Philips hue: request 32: 200 OK
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature. 
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature.

**Comment by ilcato** [comment]
@ChrisBuHa, can you test calling the GET /panels/heating/{heatingID} for some of your panels ? Use the button TRY IT!

**Comment by ChrisBuHa** [comment]
@ilcato: 

**GET heating:** 

[
  {
    "id": 4,
    "name": "Heizzone Herrenzimmer",
    "mode": "Schedule",
    "properties": {
      "handTemperature": 0,
      "handTimestamp": 0,
      "vacationTemperature": 0,
      "currentTemperature": 18
    }
  },
  {
    "id": 5,
    "name": "Heizzone Dachgeschoss",
    "mode": "Schedule",
    "properties": {
      "handTemperature": 0,
      "handTimestamp": 0,
      "vacationTemperature": 0,
      "currentTemperature": 24
    }
  },
  {
    "id": 6,
    "name": "Heizzone KZ Till",
    "mode": "Schedule",
    "properties": {
      "handTemperature": 0,
      "handTimestamp": 0,
      "vacationTemperature": 0,
      "currentTemperature": 20
    }
  },
  {
    "id": 7,
    "name": "Heizzone Saunaraum",
    "mode": "Schedule",
    "properties": {
      "handTemperature": 0,
      "handTimestamp": 0,
      "vacationTemperature": 0,
      "currentTemperature": 17
    }
  },
  {
    "id": 8,
    "name": "Heizzone Kellerflur",
    "mode": "Schedule",
    "properties": {
      "handTemperature": 0,
      "handTimestamp": 0,
      "vacationTemperature": 0,
      "currentTemperature": 17
    }
  },
  {
    "id": 9,
    "name": "Heizzone KZ Hannah",
    "mode": "Schedule",
    "properties": {
      "handTemperature": 0,
      "handTimestamp": 0,
      "vacationTemperature": 0,
      "currentTemperature": 20
    }
  },
  {
    "id": 10,
    "name": "Heizzone Elternschlafzimmer",
    "mode": "Schedule",
    "properties": {
      "handTemperature": 0,
      "handTimestamp": 0,
      "vacationTemperature": 0,
      "currentTemperature": 20
    }
  },
  {
    "id": 81,
    "name": "Temperature in Badezimmer",
    "mode": "Schedule",
    "properties": {
      "handTemperature": 0,
      "handTimestamp": 0,
      "vacationTemperature": 0,
      "currentTemperature": 24
    }
  }
]
Response Code

**GET HeatingID (for heating zone 81)**

{
  "id": 81,
  "name": "Temperature in Badezimmer",
  "mode": "Schedule",
  "properties": {
    "monday": {
      "morning": {
        "hour": 7,
        "minute": 15,
        "temperature": 19
      },
      "day": {
        "hour": 17,
        "minute": 30,
        "temperature": 22
      },
      "evening": {
        "hour": 21,
        "minute": 30,
        "temperature": 18
      },
      "night": {
        "hour": 4,
        "minute": 45,
        "temperature": 24
      }
    },
    "tuesday": {
      "morning": {
        "hour": 7,
        "minute": 15,
        "temperature": 19
      },
      "day": {
        "hour": 17,
        "minute": 30,
        "temperature": 22
      },
      "evening": {
        "hour": 21,
        "minute": 30,
        "temperature": 18
      },
      "night": {
        "hour": 4,
        "minute": 45,
        "temperature": 24
      }
    },
    "wednesday": {
      "morning": {
        "hour": 7,
        "minute": 15,
        "temperature": 19
      },
      "day": {
        "hour": 17,
        "minute": 30,
        "temperature": 22
      },
      "evening": {
        "hour": 21,
        "minute": 30,
        "temperature": 18
      },
      "night": {
        "hour": 4,
        "minute": 45,
        "temperature": 24
      }
    },
    "thursday": {
      "morning": {
        "hour": 7,
        "minute": 15,
        "temperature": 19
      },
      "day": {
        "hour": 17,
        "minute": 30,
        "temperature": 22
      },
      "evening": {
        "hour": 21,
        "minute": 30,
        "temperature": 18
      },
      "night": {
        "hour": 4,
        "minute": 45,
        "temperature": 24
      }
    },
    "friday": {
      "morning": {
        "hour": 7,
        "minute": 15,
        "temperature": 19
      },
      "day": {
        "hour": 17,
        "minute": 30,
        "temperature": 22
      },
      "evening": {
        "hour": 21,
        "minute": 30,
        "temperature": 18
      },
      "night": {
        "hour": 4,
        "minute": 45,
        "temperature": 24
      }
    },
    "saturday": {
      "morning": {
        "hour": 8,
        "minute": 30,
        "temperature": 19
      },
      "day": {
        "hour": 17,
        "minute": 30,
        "temperature": 22
      },
      "evening": {
        "hour": 21,
        "minute": 30,
        "temperature": 18
      },
      "night": {
        "hour": 4,
        "minute": 45,
        "temperature": 24
      }
    },
    "sunday": {
      "morning": {
        "hour": 8,
        "minute": 30,
        "temperature": 19
      },
      "day": {
        "hour": 17,
        "minute": 30,
        "temperature": 22
      },
      "evening": {
        "hour": 21,
        "minute": 30,
        "temperature": 18
      },
      "night": {
        "hour": 4,
        "minute": 45,
        "temperature": 24
      }
    },
    "handTemperature": 0,
    "handTimestamp": 0,
    "vacationTemperature": 0,
    "currentTemperature": 24,
    "rooms": [
      16
    ]
  },
  "created": 1638547105,
  "modified": 1638547105
}

**Comment by ChrisBuHa** [comment]
@ilcato: Tried your new beta,. HB started correctly, no error messages. 

Now the HB shows for all heating zones 0°C.
 
![heating zones homecenter](https://user-images.githubusercontent.com/94866088/144974309-e590350c-09bb-40a6-aed2-4fb804466089.png)

**Comment by ilcato** [comment]
@ChrisBuHa, ok the currentTemperature property is the one that I need! Give me a couple of hours...

**Comment by ilcato** [comment]
@ChrisBuHa, can you test the new beta?

**Comment by ChrisBuHa** [comment]
@ilcato I have installed latest beta.

![heating zones homecenter](https://user-images.githubusercontent.com/94866088/144991732-b1c57992-70a9-48af-8920-1d315126137a.png)

Now the temperatures are shown correctly.

But still have the following messages in the log.

[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature.
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature.
[06/12/2021, 20:04:48] [FibaroHC] No value for Temperature.

**Comment by ilcato** [comment]
@ChrisBuHa, can you test the new beta?

**Comment by ChrisBuHa** [comment]
@ilcato: tested your latest beta. 

![heating zones homecenter](https://user-images.githubusercontent.com/94866088/145019997-b3e1182c-865f-4e7e-939f-ac661212ff98.png)

Now the temperatures of the heating zones are shown correctly and I can change them in the HomeKit app. After chaging, the predefinded temperature of the heating zone is overwritten with the manually defined value and the heating schedule is set to manual mode for 2 hours. 

But it is currently not possible to deactive the manual mode again, e.g. by choosing "auto", It would be great if it is possible that the thermostat then switches back to the preset temperatur of the heating schedule. Maybe the standard operation status while unsing the heating schedule is "auto" and if the temperature of the heating zone is changed manually then it is status "heating"

![1](https://user-images.githubusercontent.com/94866088/145020725-fd0c45f6-60e1-43db-b9d5-55e45d38d68c.png)

Do you see any possibility to implement to activate the vacation mode for the heating zones? Maybe by choosing "off" in the menu shown in the picture above? 

And is it maybe possible to display the actual status of the thermostats (set temperatur, heating or off)? Of cause the temperature and status would be definded via heating zone groups, but if the set temperatur would be visible for each thermostat, it would be helpful to identify if every thermostat is working correctly. 
In the past I sometimes had the problem, that the command to change the temperatur (e.g. according to the heating schedule) has not always recognized by my thermostats. 
So if both values set temperatur in heating zone and real set temperatur of the thermostat would be visible, then I could directly see that everything is working fine. 





![3](https://user-images.githubusercontent.com/94866088/145022996-fb8c4a00-37c9-4412-b0fe-d0eabe8926b1.png)

In the picture above both the set temperatur and status of the thermostat are not correct. According to the heating zone "Dachgeschoss", the set temperatur should be 23.5 and mode status should be "heating". he values reported back by the thermostat are therefore not the same as the actual values that can be read from the thermostat.


Thanks for your effort! I really appreciate it.

**Comment by ilcato** [comment]
> Now the temperatures of the heating zones are shown correctly and I can change them in the HomeKit app. After chaging, the predefinded temperature of the heating zone is overwritten with the manually defined value and the heating schedule is set to manual mode for 2 hours.

This is the intended behaviour. The 2 hours period is configurable with the `thermostattimeout` parameter in config.json.

> But it is currently not possible to deactive the manual mode again, e.g. by choosing "auto", It would be great if it is possible that the thermostat then switches back to the preset temperatur of the heating schedule. Maybe the standard operation status while unsing the heating schedule is "auto" and if the temperature of the heating zone is changed manually then it is status "heating"

The `off`, `heat`, `cool` and `auto` option in the HomeKit UI are relative to the thermostat mode. The `auto` mode means switch between `heat` and `cool` based on the selected target temperature. In the case of the HC2 it is meaningless. 

> Do you see any possibility to implement to activate the vacation mode for the heating zones? Maybe by choosing "off" in the menu shown in the picture above?

Same as before, I don't want to give a custom semantic to the HomeKit mode.



> In the picture above both the set temperatur and status of the thermostat are not correct. According to the heating zone "Dachgeschoss", the set temperatur should be 23.5 and mode status should be "heating". he values reported back by the thermostat are therefore not the same as the actual values that can be read from the thermostat.

Not sure to understand. I cannot change the UI of the HomeKit widget.

I'm going to publish this version for now.

**Comment by ChrisBuHa** [comment]
> The `off`, `heat`, `cool` and `auto` option in the HomeKit UI are relative to the thermostat mode. The `auto` mode means switch between `heat` and `cool` based on the selected target temperature. In the case of the HC2 it is meaningless.
> 

Thanks for your explanation. OK now the function of `cool`, `heat` and `auto` are clear. But what is `off` intended to do for the heating zone? Can I deactivate the heating zone or heating schedule with it or ist it also meaningless for heating zones? 


> > In the picture above both the set temperatur and status of the thermostat are not correct. According to the heating zone "Dachgeschoss", the set temperatur should be 23.5 and mode status should be "heating". he values reported back by the thermostat are therefore not the same as the actual values that can be read from the thermostat.

> Not sure to understand. I cannot change the UI of the HomeKit widget.

Please excuse my poor wording. Of cause you cannot change the UI of the widget. What I wanted to say is, that the value of the set temperatur and the status of the thermostat is not correct in the Thermostat widget ( in the Heating zone widget they are correct)

The temperatur is set to 23.5°C via heating zone widget for the heating zone "Dachgeschoss" and the thermostat status is "heating". 

![heating zone](https://user-images.githubusercontent.com/94866088/145057649-73b4ba42-1911-4cc8-af82-e153a58b64d4.png)

In the widget of the thermostat which is assinged to the heating zone "Dachgeschoss", the set temperatur whereas is 20.2°C and the thermostat status is "off".  That does not correspond to the values set in the heating zone widget.


![thermostat](https://user-images.githubusercontent.com/94866088/145058060-6c6a9b30-8655-4c01-ae94-bc4c6ec5e1fe.png)

The thermostat widged seems not to be updated correctly with the values set in the heating zone widget, although they are correctly transferred to the HC2

![homecenter](https://user-images.githubusercontent.com/94866088/145058868-68e766f0-8df0-4904-8b34-729613bc2c2d.png)
